---
# tasks for clamscan
- name: Install clamav from the epel repository
  ansible.builtin.dnf:
    name: clamav
    state: present

- name: Set av definition database directory
  ansible.builtin.lineinfile:
    path: /etc/clamd.d/scan.conf
    regexp: '^#DatabaseDirectory'
    line: "{{ db_dir }}"

- name: Get current selinux label on /usr/local/clamav
  ansible.builtin.command: ls -laZ /usr/local/clamav
  register: clam_label
  tags:
    - selinux

- name: Debug out
  ansible.builtin.debug:
    var: clam_label.stdout
  tags:
    - selinux

- name: Set appropiate SELinux file context on /usr/local/clamav
  community.general.sefcontext:
    target: "/usr/local/clamav(/.*)?"
    setype: antivirus_db_t
    state: present
  when: "'antivirus_db_t' not in clam_label.stdout"
  tags:
    - selinux

- name: Create local report directory
  ansible.builtin.file:
    path: /usr/local/clamav/reports
    state: directory
    owner: root
    group: "{{ auditors }}"
    mode: '0650'

- name: Create local quarantine directory
  ansible.builtin.file:
    path: /usr/local/clamav/quarantine
    state: directory
    owner: root
    group: "{{ auditors }}"
    mode: '0650'

- name: Copy clamscan.sh script to remote host
  ansible.builtin.template:
    src: ./roles/clamscan/templates/clamscan.j2
    dest: /bin/clamscan.sh
    owner: root
    group: root
    mode: '0700'
  tags:
    - template

- name: create cronjob for weekly scan
  ansible.builtin.cron:
    name: clamscan
    weekday: "6"
    minute: "0"
    hour: "5"
    user: root
    job: "/bin/clamscan.sh"
    cron_file: clamscan

